<?php

/**
 * @file
 * Contains condition_field.module.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\condition_field\Hook\ConditionFieldHooks;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
#[LegacyHook]
function condition_field_help($route_name, RouteMatchInterface $route_match) {
  return \Drupal::service(ConditionFieldHooks::class)->help($route_name, $route_match);
}
